koguma {
  data-source {
    guild {
      default = me.ghostbear.koguma.data.mediaQueryAnilist.dataSource.AniListMediaDataSource
      config = []
      config = ${?KOGUMA_DATA_SOURCE_GUILD_CONFIG[]}
    }
  }
  token = ${?KOGUMA_TOKEN}
}