koguma {
  data-source {
    guild {
      default = me.ghostbear.koguma.data.mediaQueryAnilist.dataSource.AniListMediaDataSource
      config = []
      config = ${?KOGUMA_DATA_SOURCE_GUILD_CONFIG[]}
    }
  }
  media-query {
    media-link-ids = [anilist, myanimelist, kitsu]
    media-link-ids = ${?KOGUMA_MEDIA_QUERY_MEDIA_LINK_IDS[]}
  }
  token = ${?KOGUMA_TOKEN}
}